name1 = input("請輸入第一位學生的姓名：")
score1 = int(input("請輸入第一位學生的成績: "))
name2 = input("請輸入第二位學生的姓名：")
score2 = int(input("請輸入第二位學生的成績: "))
print()
print("姓名    成績")
print("%-4s  %3d" % (name1, score1))
print("%-4s  %3d" % (name2, score2))
print("成績總分為：" + str(score1 + score2))